secret_root: '{{ inventory_dir | realpath }}'
secret_name: 'secret'
secret: '{{ secret_root + "/" + secret_name }}'
encfs_password: "{{ lookup('password', secret + '/' + 'encfs_password', length=32) }}"
