all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
solarchemist:
  hosts:
    mail.solarchemist.se: 
      ansible_ssh_host: suez
      parentdomain: solarchemist.se
      external_ipv4: 
      external_ipv6: 
# asks:
#   hosts:
#     mail.asks.se:
#       ansible_ssh_host: nuweiba
#       external_ipv4: 
#       external_ipv6: 
