---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  user: deploy
  become: True
  gather_facts: True

  roles:
    - common      # from shared ansible repo
    - locales     # from shared ansible repo
    # - encfs  
    # - postgres 
    - ufw
    - security
    - apache      # from shared ansible repo
    - mailserver  
    # - webmail     # horribly outdated as-is. Switch to package, and drop postgresql for mail user tables?
    # - tarsnap
    # - monitoring  # Monitoring role should be last. See roles/monitoring/README.md
