---

# https://z-push.org/
# WE PROBABLY SHOULD SWITCH TO z-push REPOS INSTEAD OF TARBALLS
# https://wiki.z-hub.io/display/ZP/Installation

# Z-Push is an open-source application to synchronize ActiveSync compatible devices such as mobile phones, tablets and Outlook 2013 and above. With a history of over 9 years of successful synchronization with multiple backends Z-Push is the leading open source push synchronization.
# Z-Push is an implementation of Microsoft’s ActiveSync protocol which is used 'over-the-air' for multi platform ActiveSync capable devices.

- name: Install required packages for Z-Push
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - php-soap
    - "php{{ php_default_version_debian }}"
    - "php{{ php_default_version_debian }}-cli"
    - "php{{ php_default_version_debian }}-imap"
  tags:
    - dependencies

- name: Download Z-Push release
  get_url:
    url: "http://download.z-push.org/final/2.1/z-push-{{ zpush_version }}.tar.gz"
    dest: "/root/z-push-{{ zpush_version }}.tar.gz"

- name: Decompress Z-Push source
  unarchive: 
    src: "/root/z-push-{{ zpush_version }}.tar.gz"
    dest: /root
    copy: no
  args:
    creates: "/root/z-push-{{ zpush_version }}"

- name: Create /usr/share/z-push
  file: 
    state: directory
    path: /usr/share/z-push

- name: Copy Z-Push source files to /usr/share/z-push
  shell: "cp -R z-push-{{ zpush_version }}/* /usr/share/z-push/"
  args: 
    chdir: /root
  tags:
    - skip_ansible_lint

- name: Remove downloaded, temporary Z-Push source files
  shell: rm -rf z-push*
  args:
    chdir: /root
  tags:
    - skip_ansible_lint

- name: Ensure Z-Push state and log directories are in place
  file: 
    state: directory
    path: "{{ item }}" 
    owner: www-data
    group: www-data
    mode: 0755
  with_items:
    - /decrypted/zpush-state
    - /var/log/z-push
  notify: restart apache

- name: Copy Z-Push's config.php into place
  template: 
    src: usr_share_z-push_config.php.j2
    dest: /usr/share/z-push/config.php

- name: Create Z-Push Apache alias and PHP configuration file
  copy: 
    src: etc_apache2_conf.d_z-push.conf
    dest: /etc/apache2/conf-available/z-push.conf

- name: Enable Z-Push Apache alias and PHP configuration file
  command: a2enconf z-push 
  args:
    creates: /etc/apache2/conf-enabled/z-push.conf
  notify: restart apache

- name: Configure Z-Push logrotate
  copy: 
    src: etc_logrotate_z-push 
    dest: /etc/logrotate.d/z-push 
    owner: root
    group: root
    mode: 0644
